apiVersion: apps/v1
kind: Deployment
metadata:
  name: createpod
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      restartPolicy: Always
      containers:
      - name: mongocreatepod
        image: mongo:latest
        ports:
        - containerPort: 27017
        resources :
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"