apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: all-pods-monitor
  namespace: monitoring
spec:
  selector: {}  # This selects all pods
  namespaceSelector:
    any: true   # This ensures it monitors pods across all namespaces
  podMetricsEndpoints:
    - port: http-metrics  # Ensure your pods expose metrics on this port
      interval: 30s
